### ISSUE TITLE
Transforming messages from AWS

### ISSUE THREAD

**Issue by muizsyed** [rebus-org/Rebus.AmazonSQS#11]
I have messages sent to SQS from other AWS services which cant be used with Rebus due to the format (Body field is the full body and doesnt contain a mix of header + body). Is there any plan to provide the ability to transform messages to adapt messages into something Rebus can handle?

**Comment by mookid8000** [comment]
well.... don't have anything planned

The reason it is so, is because SQS supports only 10 custom headers on each message, which is too few for Rebus to work.

It is really unfortunate, because the transport then needs to assume some more serialization-like responsibilities, which then prevents you from wedging logic in between having received the message and attempting to deserialize it.

For now, your best bet is probably to build something that manually receives those messages and then uses a Rebus one-way client to forward them to the real recipient.

**Comment by mookid8000** [comment]
If you have any other ideas on how to overcome the max 10 message attributes limit, I would love to know....

**Comment by muizsyed** [comment]
What if all rebus headers were packed into a single SQS header attribute?
Cant see anything in documentation that implies there are limits to this other than the overall message limit

**Comment by mookid8000** [comment]
I would call that solution silly and brilliant at the same time 😁 it should be pretty easy to try and do that. If I get the time, I can try and do it one of the following days.
