### ISSUE TITLE
Error sending too many messages to SQS with version 4.01 

### ISSUE THREAD

**Issue by dbierbaum** [rebus-org/Rebus.AmazonSQS#15]
We have many threads which share the same IBus instance. This worked fine with version 3.0 of Rebus.AmazonSQS but as soon as we upgraded to version 4.0.1 we ran into a problem with messages failing to send when we attempt to process larger batches of items:

2018-01-09 15:54:32,898 [8] WARN Rebus.Retry.ErrorTracking.InMemErrorTracker - Unhandled exception 1 while handling message with ID "50494559-d298-41b4-bdde-8933a4acda7a"
Amazon.SQS.Model.TooManyEntriesInBatchRequestException: Maximum number of entries per request are 10. You have sent 48. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request

I saw nothing in the config which would allow us to restrict Rebus to only send 10 messages at a time. Also I'm curious why this was logged as a warning, shouldn't it be an error since the messages were not sent?

**Comment by mookid8000** [comment]
WTF?! so the transport just logged it as a warning and went on with its thing? that's definitely not the intended behavior..... I'll take a look at it

**Comment by mookid8000** [comment]
Ah, now I understand – if you look at this

2018-01-09 15:54:32,898 [8] WARN Rebus.Retry.ErrorTracking.InMemErrorTracker - Unhandled exception 1 while handling message with ID "50494559-d298-41b4-bdde-8933a4acda7a"
Amazon.SQS.Model.TooManyEntriesInBatchRequestException: Maximum number of entries per request are 10. You have sent 48. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request

you should pay attention to the first part:

2018-01-09 15:54:32,898 [8] WARN Rebus.Retry.ErrorTracking.InMemErrorTracker - **Unhandled exception 1 while handling message with ID "50494559-d298-41b4-bdde-8933a4acda7a"**
Amazon.SQS.Model.TooManyEntriesInBatchRequestException

IOW the warning is logged because message handling failed the first time ("exception 1") out of all of the possible delivery attempts (default: 5) – it's not logged by the transport 😄 

I have fixed the missing batching bug by limiting batches of outgoing messages to 10.... it'll be out in 4.0.2 as soon as CI has finished munching through the tests.

Thanks for reporting this! 👍

**Comment by dbierbaum** [comment]
we tested the new version with our app and it works great now, thank you for the super fast resolution! Rebus rocks! 😎
