### ISSUE TITLE
No possibility to add custom headers

### ISSUE THREAD

**Issue by mvandevy** [rebus-org/Rebus.AmazonSQS#4]
By default Rebus uses about 8 headers, which it adds to each message. The number of headers is increased by 2 whenever a message is poisonous. So by the time it reaches the poison queue it has 10 headers. 10 is however the upper limit of the number of headers allowed on an SQS message. See: 'http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-attributes.html' which states: 

> Each message can have up to 10 attributes.

As a result you are no longer possible to add your own header(s) to a message. What actually happens is that when you've added an additional header, so you have 9. And the message is poisonous, then the failing message can't even be placed on the poison queue. Rebus stays in a perpetual retry 😢 

I would propose to have a additional configuration option which would tell the SQS transport to pack the 'known' rebus header into a single header attribute on SQS. This would allow you add up to at least 9 custom header. On the receiving side the SQS library would just need to check for the 'packed together key' in order to know how to parse the headers. 

I can create a pull request for this as I've already solved the issue as described above, but I'd like to know if this is a good approach.

**Comment by mookid8000** [comment]
aww bummer dude! – your suggested solutions sounds really nice, actually, but I think I need to think a little bit about this..... brb 😄

**Comment by mvandevy** [comment]
Created a PR with a 'possible' solution to the issue.

**Comment by mookid8000** [comment]
#5  looks pretty good, and I can definitely see how this solution could work. It just bothers me that the user then needs to predict the number of headers before setting up Rebus with SQS in order to configure whether headers should be packed.

I can see that the `SendMessageBatchRequestEntry` has a field for the message ID – so there's one header that can be saved 😄

**Comment by mookid8000** [comment]
In the docs it states that the size of the message cannot exceed 256 kB.  Both message attributes and the body count towards this limit.

IIRC the Azure Storage Queues transport packs transport messages into a single JSON string, something like this:

    {
        "headers": {
            "whee": "good stuff"
        },
        "body": "3yg873BASE64andstuff"
    }

Wouldn't it be better to do that with SQS too? And then simply ditch the built-in attributes because they have stupid arbitrary limitations (max 10, cannot start with the string 'aws', cannot contain two successive .s, etc.)....

What do you think about this idea?

**Comment by mvandevy** [comment]
I guess your suggestion would work as well, with the added benefit that you're no longer constrained with 10 being the maximum number of headers allowed. 

The main disadvantage with pushing the headers to the body of the message is that the headers are no longer human readable when you switch to an alternative serialization mechanism, like protobuf, or even when you encode the body to base64. You can't really peek into the messages whenever something goes wrong. That's why I smashed the headers together.

Another alternative is to have all non-core Rebus headers moved to the body, while keeping the core rebus headers in the current header attributes?

**Comment by mvandevy** [comment]
Played around with the code and performed a test run which allowed me to create messages as you stated above. As an example, this is het body of the message:

`{"headers":{"rbs2-msg-id":"66d63a56-56b4-442e-8c27-cccb84ce23ba","rbs2-corr-id":"56b44407-398b-487a-b41b-fdd649e10fd0"},"body":"aGVq"}`

No message attributes were added. I also had a closer look at the protobuf serializer, and it seems only the body is serialized, not the headers, which basically solves the issue about human readability I was talking about.

I'll put together a new pull request with these changes.

**Comment by mookid8000** [comment]
Fixed by #6 😄
